version: "3.8"
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_USERNAME}"
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
      - ../frontend:/opt/app/frontend
    environment:
      POSTGRES_HOST: "10.5.0.2"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1